// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$3K17kjT.g9XdQx6Kl3ooCulOPQN1U5PckcDF.E/xm0cqSNXFjr/2G",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 2, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$XLRrpiYqqC.5/.QecCzTFeNGa.FHhv/QTPntyVxYvTm2.kBCcv2lm",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "priya.prabhu@xyz.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Prabhu",
                            Phone = "9876543210",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 2, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "arjun.sharma@xyz.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sharma",
                            Phone = "9812345678",
                            Salary = 620000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 2, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 3, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "neha.kapoor@xyz.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kapoor",
                            Phone = "9823456789",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 3, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 4, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "rahul.verma@xyz.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Verma",
                            Phone = "9834567890",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 4, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "sneha.prasad@xyz.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Prasad",
                            Phone = "9845678901",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 6, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Senior Developer",
                            Email = "vikram.raj@xyz.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Raj",
                            Phone = "9856789012",
                            Salary = 1100000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 6, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 7, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "ananya.singh@xyz.com",
                            FirstName = "Ananya",
                            JoinDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Singh",
                            Phone = "9867890123",
                            Salary = 580000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 7, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 8, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Accounts Manager",
                            Email = "karthik.rajan@xyz.com",
                            FirstName = "Karthik",
                            JoinDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rajan",
                            Phone = "9878901234",
                            Salary = 800000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 8, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 9, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "Talent Acquisition",
                            Email = "divya.kumar@xyz.com",
                            FirstName = "Divya",
                            JoinDate = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kumar",
                            Phone = "9889012345",
                            Salary = 690000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 9, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 10, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "DevOps Engineer",
                            Email = "rohan.mehta@xyz.com",
                            FirstName = "Rohan",
                            JoinDate = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Mehta",
                            Phone = "9890123456",
                            Salary = 920000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 11, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Brand Manager",
                            Email = "lakshmi.chandran@xyz.com",
                            FirstName = "Lakshmi",
                            JoinDate = new DateTime(2021, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Chandran",
                            Phone = "9801234567",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 11, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 12, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Tax Consultant",
                            Email = "suresh.babu@xyz.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Babu",
                            Phone = "9811223344",
                            Salary = 680000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 12, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 13, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "meera.krishnan@xyz.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2020, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Krishnan",
                            Phone = "9822334455",
                            Salary = 710000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 13, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 14, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Supply Chain Analyst",
                            Email = "amit.joshi@xyz.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2023, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Joshi",
                            Phone = "9833445566",
                            Salary = 630000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 14, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 15, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Process Engineer",
                            Email = "pooja.ghosh@xyz.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Ghosh",
                            Phone = "9844556677",
                            Salary = 870000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 15, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
